# WORK ON MULTIPLE PROJECTS ON SERVICE BASED COMPONYE'S
# GROW
# STAY BUSY
# STAY LEARNING
# STAY HUNGRY
# 1 LANGUAGE 1 PLATFORM
# STUCK TO PRACTICING
# IMPROVE SKILLS
# SOLE PYQ
# BACK TO THE BASICS
# OOPS STRING DATA STRUCTURE CERTIFICATION PROGRAMME
# UDEMY CERTIFICATION, DO IT. . . UPDATE OF LINKEDIN GIT GITHUB
# FOCUSED AND UPSKILL

# GIVEN AN ARRAY OF INTEGERS WHICH IS INITIALLY INCREASING AND THEN DECREASING ,
# FIND THE MAXIMUM VALUE IN THE ARRAY
# 